name: restaurant_pos
description: "A new Flutter project."
publish_to: 'none'
version: 2.2.0

environment:
  sdk: ^3.5.4

dependencies:
  auto_route: ^10.1.2
  collection: ^1.19.1
  connectivity_plus: ^7.0.0
  country_code_picker: ^3.4.0
  dio: ^5.9.0
  dotted_border: ^3.1.0
  dropdown_button2: ^2.3.9
  equatable: ^2.0.7
  esc_pos_utils_plus: ^2.0.4
  faker: ^2.2.0
  fdevs_fitkit: ^0.0.1+4
  feather_icons: ^1.2.0
  fl_chart: ^1.0.0
  flag: ^7.0.0
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  flutter_riverpod: ^2.6.1
  flutter_slidable: ^4.0.0
  flutter_svg: ^2.2.0
  flutter_widget_from_html: ^0.17.0
  form_builder_validators: ^11.2.0
  hugeicons: ^1.0.2
  iconly: ^1.0.1
  icons_plus: ^5.0.0
  image_picker: ^1.2.0
  flutter_image_compress: ^2.3.0
  cached_network_image: ^3.4.1
  infinite_scroll_pagination: ^4.1.0
  intl: ^0.20.2
  # open_filex: ^4.7.0
  path: ^1.9.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  pinput: ^5.0.1
  pretty_dio_logger: ^1.4.0
  print_bluetooth_thermal: ^1.1.6
  printing: ^5.14.2
  shared_preferences: ^2.5.3
  simple_barcode_scanner: ^0.3.0
  skeletonizer: ^2.1.0
  slang: ^4.8.1
  slang_flutter: ^4.8.0
  smooth_page_indicator: ^1.2.1
  persistent_header_adaptive: ^2.1.3
  expansion_widget: ^0.1.0
  searchfield: ^1.3.3
  universal_image: ^1.0.11
  permission_handler: ^11.3.1
  qr_flutter: ^4.1.0
  lottie: ^3.3.1
  image: ^4.5.4
  share_plus: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  auto_route_generator: ^10.2.4
  build_runner: ^2.7.0
  rename_app: ^1.6.5
  change_app_package_name: ^1.5.0
  icons_launcher: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/app/
    - assets/images/onboard/
    - assets/shapes/
    - assets/icons/drawer_icons/
    - assets/icons/svg_icons/
    - assets/icons/payment_icons/
    - assets/lottie/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: fonts/Poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        
scripts:
  customize: dart lib/dev_tool/.customize.dart